config/routes.rb
Rails.application.routes.draw do
  resources :productos
  resources :personas
  devise_for :users
  get 'home/index'

  resources :tipo_productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get 'productos', to: "productos#index"

  get 'proveedores', to: "personas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/persona.rb
class Persona < ApplicationRecord
  has_many :productos, dependent: :destroy
end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :tipo_producto
  belongs_to :persona
  has_attached_file :image, styles: { medium: "50x50#", thumb: "450x450>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/tipo_producto.rb
class TipoProducto < ApplicationRecord
  has_attached_file :image, styles: { medium: "200x200#", thumb: "450x450>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :productos, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tipo_productos = TipoProducto.all
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:num_documento, :nombre, :apellido, :direccion, :telefono, :email)
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :precio_compra, :precio_venta, :descripcion, :tipo_producto_id, :persona_id, :image)
    end
end

app/controllers/tipo_productos_controller.rb
class TipoProductosController < ApplicationController
  before_action :set_tipo_producto, only: [:show, :edit, :update, :destroy]

  # GET /tipo_productos
  # GET /tipo_productos.json
  def index
    @tipo_productos = TipoProducto.all
  end

  # GET /tipo_productos/1
  # GET /tipo_productos/1.json
  def show
  end

  # GET /tipo_productos/new
  def new
    @tipo_producto = TipoProducto.new
  end

  # GET /tipo_productos/1/edit
  def edit
  end

  # POST /tipo_productos
  # POST /tipo_productos.json
  def create
    @tipo_producto = TipoProducto.new(tipo_producto_params)

    respond_to do |format|
      if @tipo_producto.save
        format.html { redirect_to @tipo_producto, notice: 'Tipo producto was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_producto }
      else
        format.html { render :new }
        format.json { render json: @tipo_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_productos/1
  # PATCH/PUT /tipo_productos/1.json
  def update
    respond_to do |format|
      if @tipo_producto.update(tipo_producto_params)
        format.html { redirect_to @tipo_producto, notice: 'Tipo producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_producto }
      else
        format.html { render :edit }
        format.json { render json: @tipo_producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_productos/1
  # DELETE /tipo_productos/1.json
  def destroy
    @tipo_producto.destroy
    respond_to do |format|
      format.html { redirect_to tipo_productos_url, notice: 'Tipo producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_producto
      @tipo_producto = TipoProducto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_producto_params
      params.require(:tipo_producto).permit(:nombre, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/tipo_productos_helper.rb
module TipoProductosHelper
end

app/views/home/index.html.erb
<h1 style="color:#0101DF";>Tipo Productos</h1>
<br><hr>
<% if user_signed_in?%>
<div class="container">
  <div class="row">
      <div class="col">
        <% @tipo_productos.each do |tipo_producto| %>
          <figure class="figure">
            <%= link_to (image_tag tipo_producto.image.url(:medium)), tipo_producto %>
              <figcaption class="figure-caption">
                  <strong><%= tipo_producto.nombre %></strong>
                  <%= link_to 'Edit', edit_tipo_producto_path(tipo_producto)%>
                  <%= link_to 'Destroy', tipo_producto, method: :delete, data: { confirm: 'Are you sure?' } %>
                </figcaption>
            </figure>
          <% end %>
      </div>
    </div>
  </div>
<br>

<%= link_to 'New Tipo Producto', new_tipo_producto_path, class: 'btn btn-primary' %>
<br><br><br>
<% else %>
  <div class="container">
    <div class="row">
        <div class="col">
          <% @tipo_productos.each do |tipo_producto| %>
            <figure class="figure">
              <%= link_to (image_tag tipo_producto.image.url(:medium)), tipo_producto %>
                <figcaption class="figure-caption">
                    <strong><%= tipo_producto.nombre %></strong>
                  </figcaption>
              </figure>
            <% end %>
        </div>
      </div>
    </div>
  <br><br><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Supermercado</title>
    <%= csrf_meta_tags %>

    <link href="/assets/application.scss" media="all" rel="stylesheet" data-turbolinks-track="true" />
    <script src="/assets/application.js" data-turbolinks-track' => true ></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <!-- Custom styles for this template -->
    </head>

    <body>

      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <h4><%= link_to 'Supermercado', root_path, style: 'color:#FFFFFF;' %></h4>&nbsp;&nbsp;
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Proveedores', proveedores_path, style: 'color:#FFFFFF;' %>&nbsp;&nbsp;&nbsp;&nbsp;
            </li>
            <li class="nav-item active">
              <%= link_to 'Productos', productos_path, style: 'color:#FFFFFF;' %>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in?%>
              <li class="nav-item active">
                <%= link_to 'Cerrar', destroy_user_session_path, method: :delete, style: 'color:#FFFFFF;' %>
              </li>
            <% else %>
              <li class="nav-item active">
                <%= link_to 'Iniciar', new_user_session_path, style: 'color:#FFFFFF;' %>&nbsp;&nbsp;&nbsp;&nbsp;
              </li>
              <li class="nav-item">
                <%= link_to 'Registrarse', new_user_registration_path , style: 'color:#FFFFFF;'%>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <main role="main" class="container">
        <div class="col-md-12">
          <br><br><br>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </main>

      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
  </html>

app/views/personas/_form.html.erb
<%= form_with(model: persona, local: true) do |form| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :num_documento %>
    <%= form.text_field :num_documento, id: :persona_num_documento, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :persona_nombre, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :apellido %>
    <%= form.text_field :apellido, id: :persona_apellido, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :direccion %>
    <%= form.text_field :direccion, id: :persona_direccion, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :persona_telefono, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, id: :persona_email, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Registrar proveedor', :class => 'btn btn-primary' %>
  </div>
<% end %>
<br>

app/views/personas/edit.html.erb
<h1>Editar Proveedor</h1>
<% if user_signed_in?%>
<%= render 'form', persona: @persona %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>
<% end %>

app/views/personas/index.html.erb
<h1 style="color:#0101DF";>Personas</h1>
<% if user_signed_in?%>
<table class="table">
  <thead>
    <tr>
      <th>Num documento</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.num_documento %></td>
        <td><%= persona.nombre %></td>
        <td><%= persona.apellido %></td>
        <td><%= persona.direccion %></td>
        <td><%= persona.telefono %></td>
        <td><%= persona.email %></td>
        <td><%= link_to 'Show', persona , class: 'btn btn-primary'%></td>
        <td><%= link_to 'Edit', edit_persona_path(persona), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path, class: 'btn btn-primary' %>
<% else %>
<table class="table">
  <thead>
    <tr>
      <th>Num documento</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.num_documento %></td>
        <td><%= persona.nombre %></td>
        <td><%= persona.apellido %></td>
        <td><%= persona.direccion %></td>
        <td><%= persona.telefono %></td>
        <td><%= persona.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/personas/new.html.erb
<h1>New Proveedor</h1>
<% if user_signed_in?%>
<%= render 'form', persona: @persona %>

<%= link_to 'Back', personas_path %>
<br><br>
<% end %>

app/views/personas/show.html.erb
<h1>New Proveedor</h1>
<% if user_signed_in?%>
<p>
  <strong>Num documento:</strong>
  <%= @persona.num_documento %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @persona.apellido %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @persona.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @persona.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @persona.email %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>
<% end %>

app/views/productos/_form.html.erb
<%= form_with(model: producto, local: true) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :producto_nombre, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :precio_compra %>
    <%= form.text_field :precio_compra, id: :producto_precio_compra, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :precio_venta %>
    <%= form.text_field :precio_venta, id: :producto_precio_venta, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :producto_descripcion, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :tipo_producto_id %>
    <%= form.collection_select :tipo_producto_id, TipoProducto.order(:nombre),:id, :nombre, include_blank: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :persona_id %>
    <%= form.collection_select :persona_id, Persona.order(:nombre),:id, :nombre, include_blank: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :imagen %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit 'Registrar producto', :class => 'btn btn-primary' %>
  </div>
<% end %>
<br>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>
<% if user_signed_in?%>
<%= render 'form', producto: @producto %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>
<% end %>

app/views/productos/index.html.erb
<h1 style="color:#0101DF";>Productos</h1>
<% if user_signed_in?%>
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio compra</th>
      <th>Precio venta</th>
      <th>Descripcion</th>
      <th>Tipo producto</th>
      <th>Proveedor</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.precio_compra %></td>
        <td><%= producto.precio_venta %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.tipo_producto.nombre %></td>
        <td><%= producto.persona.nombre %></td>
        <td><%= link_to (image_tag producto.image.url(:medium))%></td>
        <td><%= link_to 'Show', producto, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto), class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path, class: 'btn btn-primary' %>
<% else %>
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio venta</th>
      <th>Descripcion</th>
      <th>Tipo producto</th>
      <th>Proveedor</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.precio_venta %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.tipo_producto.nombre %></td>
        <td><%= producto.persona.nombre %></td>
        <td><%= link_to (image_tag producto.image.url(:medium))%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/productos/new.html.erb
<h1>New Producto</h1>
<% if user_signed_in?%>
<%= render 'form', producto: @producto %>

<%= link_to 'Back', productos_path %>
<br><br>
<% end %>

app/views/productos/show.html.erb
<% if user_signed_in?%>
<%= image_tag @producto.image.url(:medium)%>
<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Precio compra:</strong>
  <%= @producto.precio_compra %>
</p>

<p>
  <strong>Precio venta:</strong>
  <%= @producto.precio_venta %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Tipo producto:</strong>
  <%= @producto.tipo_producto.nombre %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @producto.persona.nombre %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>
<% end %>

app/views/tipo_productos/_form.html.erb
<%= form_for @tipo_producto, html: { multipart: true } do |form| %>
  <% if tipo_producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_producto.errors.count, "error") %> prohibited this tipo_producto from being saved:</h2>

      <ul>
      <% tipo_producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :imagen %>
    <%= form.file_field :image %>
  </div>

  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :tipo_producto_nombre, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tipo_productos/edit.html.erb
<h1>Editar Tipo Producto</h1>
<% if user_signed_in?%>
<%= render 'form', tipo_producto: @tipo_producto %>

<%= link_to 'Show', @tipo_producto %> |
<%= link_to 'Back', tipo_productos_path %>
<br><br><br>
<% end %>

app/views/tipo_productos/index.html.erb
<h1 style="color:#0101DF";>Tipo Productos</h1>
<br><hr>
<% if user_signed_in?%>
<div class="container">
  <div class="row">
      <div class="col">
        <% @tipo_productos.each do |tipo_producto| %>
          <figure class="figure">
            <%= link_to (image_tag tipo_producto.image.url(:medium)), tipo_producto %>
              <figcaption class="figure-caption">
                  <strong><%= tipo_producto.nombre %></strong>
                  <%= link_to 'Edit', edit_tipo_producto_path(tipo_producto) %>
                  <%= link_to 'Destroy', tipo_producto, method: :delete, data: { confirm: 'Are you sure?' } %>
                </figcaption>
            </figure>
          <% end %>
      </div>
    </div>
  </div>
<br>

<%= link_to 'New Tipo Producto', new_tipo_producto_path, class: 'btn btn-primary' %>
<br><br><br>
<% else %>
  <div class="container">
    <div class="row">
        <div class="col">
          <% @tipo_productos.each do |tipo_producto| %>
            <figure class="figure">
              <%= link_to (image_tag tipo_producto.image.url(:medium)), tipo_producto %>
                <figcaption class="figure-caption">
                    <strong><%= tipo_producto.nombre %></strong>
                  </figcaption>
              </figure>
            <% end %>
        </div>
      </div>
    </div>
  <br><br><br>
<% end %>

app/views/tipo_productos/new.html.erb
<h1>New Tipo Producto</h1>
<% if user_signed_in?%>
<%= render 'form', tipo_producto: @tipo_producto %>

<%= link_to 'Back', tipo_productos_path %>
<br><br>
<% end %>

app/views/tipo_productos/show.html.erb
<% if user_signed_in?%>
<center style="color:#FF0000";><h4>
  Categoria <%= @tipo_producto.nombre%>
</h4></center><br>
<center>
    <%= image_tag @tipo_producto.image.url(:medium)%>

  <p>
    <%= link_to 'Edit', edit_tipo_producto_path(@tipo_producto) %> |
    <%= link_to 'Back', tipo_productos_path %>
  </p>
</center>

<hr>
<div>
  <% @tipo_producto.productos.each do |produ| %>
    <div class="table">
      <h4 style="color:#0101DF";>
        <%= produ.nombre%>
      </h4>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Precio compra</th>
            <th scope="col">Precio venta</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Imagen</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= produ.precio_compra %></td>
            <td><%= produ.precio_venta %></td>
            <td><%= produ.descripcion %></td>
            <td><%= image_tag produ.image.url(:medium)%></td>
          </tr>
        </tbody>
      </table>
  </div>
  <% end %>
</div>
<% else %>
<center style="color:#FF0000";><h4>
  Categoria <%= @tipo_producto.nombre%>
</h4></center><br>
<center>
    <%= image_tag @tipo_producto.image.url(:medium)%>

  <p>
    <%= link_to 'Back', tipo_productos_path %>
  </p>
</center>

<hr>
<div>
  <% @tipo_producto.productos.each do |produ| %>
    <div class="table">
      <h4 style="color:#0101DF";>
        <%= produ.nombre%>
      </h4>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Precio venta</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Imagen</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= produ.precio_venta %></td>
            <td><%= produ.descripcion %></td>
            <td><%= image_tag produ.image.url(:medium)%></td>
          </tr>
        </tbody>
      </table>
  </div>
  <% end %>
</div>
<% end %>